apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune
spec:
  selector:
    matchLabels:
      app: neptune
  template:
    metadata:
      labels:
        app: neptune
    spec:
      containers:
      - name: neptune
        image: k0rventen/neptune:latest
        resources: {}
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: "/app/data"
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neptune--perstistent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neptune--perstistent-data
spec:
  resources:
    requests:
      storage: "500Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: neptune
spec:
  selector:
    app: neptune
  ports:
  - port: 5000
    targetPort: 5000
