name: Test API with Locust

on:
  push:
    branches: [ "main" ]

jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker build & run
        run: |
          cd backend/tests
          docker compose build
          docker compose up -d neptune
          docker compose up tests
          docker compose down