name: Build Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker build & run
        run: |
          cd backend/tests
          docker compose build
      -
        name: Locust tests
        run: |
          docker compose up -d neptune
          docker compose up tests
      - 
        name: Cleanup
        run: |
          docker compose down